In [1]:
import pandas as pd

df_shops = pd.read_csv(r"C:\Users\srude\Documents\Dev Kram\Gravity_Model_neu\Data\shops_final_564m_21.11.21.csv", encoding='latin-1')
print(df_shops["Year"].unique())

ModuleNotFoundError: No module named 'pandas'

In [14]:
print(df_shops["City"].unique())

['Hamburg']

In [19]:
df_shops_2011 = df_shops[df_shops["Year"] == 2011]
df_shops_2011 = df_shops_2011[['UNIQUEID', 'ID', 'SalesSqMTotal', 'SalesSqMOrganic', 'TotalSales', 'Name', 'Location', 'Address', 'Zip', 'Type', 'TypeAg', 'Size', 'Warehouse', 'Chain','Neighborhood', 'District', 'AreaSqM', 'USERID', 'Income','NEARDIST' ]]
df_shops_2011.rename(columns={'AreaSqM':'NH_AreaSqM', "USERID": 'NH_ID'})
# Drop: LISTID, Time,  TimeLog, Year, City, Country,....
# City = Hamburg, Country = Germany, Time = 2011

,UNIQUEID,ID,SalesSqMTotal,SalesSqMOrganic,TotalSales,Name,Location,Address,Zip,Type,TypeAg,Size,Warehouse,Chain,Neighborhood,District,NH_AreaSqM,NH_ID,Income,NEARDIST
2732,211001,D11001,5450,115,2130950,Aldi,412,Hermannstal 72,22119,Discounter,Conventional,391,Aldi Nord,Aldi,Horn,Hamburg-Mitte,5851881,45,21404,2817.3
2733,211002,D11002,5450,115,2180000,Aldi,619,Moellner LandStrasse 131,22117,Discounter,Conventional,400,Aldi Nord,Aldi,Billstedt,Hamburg-Mitte,16923802,13,22219,5129.2
2734,211003,D11003,5450,115,3270000,Aldi,452,HolstenStrasse 156,22765,Discounter,Conventional,600,Aldi Nord,Aldi,Altona-Nord,Altona,2222785,6,28607,868.7
2735,211004,D11004,5450,115,3270000,Aldi,705,Paul-Roosen-Strasse 43,22767,Discounter,Conventional,600,Aldi Nord,Aldi,Altona-Altstadt,Altona,2304126,5,27436,793.1
2736,211005,D11005,5450,115,3270000,Aldi,549,Langenfelder Damm 46,22525,Discounter,Conventional,600,Aldi Nord,Aldi,Stellingen,Eimsbuettel,6084188,90,33225,546.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3221,111036,O11036,5017,5017,3010200,Tjadens Bio Frische Markt,310,GertigStrasse 26,22303,Organic Shop,Organic,600,Dennree,Other,Winterhude,Hamburg-Nord,7127776,103,46292,NaN
3222,111037,O11037,4515,4515,451500,Villa Sonnenschein,129,Boenningstedter Weg 42,22457,Organic Shop,Organic,100,Other,Other,Schnelsen,Eimsblttel,8950744,83,36104,NaN
3223,111038,O11038,4515,4515,1354500,Vitalien Naturkost,198,DorotheenStrasse 178,22299,Organic Shop,Organic,300,Grell,Other,Winterhude,Hamburg-Nord,7127776,103,55000,NaN
3224,111039,O11039,4515,4515,532770,warenwirtschaft cblk OHG,344,Grosse BrunnenStrasse 141,22763,Organic Shop,Organic,118,Other,Other,Ottensen,Altona,2551538,74,35017,NaN
3225,311008,S11008,4112,174,822400,Edeka Meyer,786,Saseler Chaussee 35,22391,Small_Full_Service,Conventional,200,Edeka Nord,Edeka,Wellingsbuettel,Wandsbek,4086550,100,57100,4543.2

In [21]:
df_shops_2011.to_csv(r'C:\Users\srude\Documents\Dev Kram\Gravity_Model_neu\Output_csv_shops\Hamburg_shops_2011.csv', index=False )